import './js/waves.js'
import './js/interactive.js'
// import './js/animations.js'
import './styles/main.scss'
import './styles/about.scss'
import './styles/projects.scss'
import './styles/contact.scss'